all:
  children:
    hardened_nodes:
      hosts:
        node01:
          ansible_host: 4.210.209.95
          ansible_user: azureadmin
          ansible_ssh_private_key_file: ~/.ssh/fp25519
      vars:
        r79_allowed_ssh_sources:
          - "209.206.8.34/32"    # Ton IP perso