---
- name: Disable IPv6
  hosts: node1
  become: true

  tasks:
    - ansible.posix.sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: '1'
        state: present
        sysctl_file: /etc/sysctl.conf
        reload: yes

    - ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        state: present
        sysctl_file: /etc/sysctl.conf
        reload: yes
...
